export BROWSERSTACK_USERNAME="${BROWSERSTACK_USERNAME}"
export BROWSERSTACK_ACCESS_KEY="${BROWSERSTACK_ACCESS_KEY}"
export BROWSERSTACK_USE_AUTOMATE="1"
export BROWSERSTACK_CAPABILITIES_CONFIG_PATH="${PWD}/browserstack-config.json"
export BROWSERSTACK_BUILD_ID="Test Build `date +%Y%m%d%H%M%S`"
echo $BROWSERSTACK_BUILD_ID